export const mockOfficerData = {
  "status": "success",
  "data": [
    {
      "_id": "687b05c7b14b994f291992c4",
      "title": "Barangay Annual Report 2024",
      "summary": "A comprehensive summary of the barangay's accomplishments, finances, and activities for the year 2024.",
      "author": "Maria Lopez",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1752892870/Government%20Archiving/68776346bc4a051d05a6c173/1752892859757_sample",
      "fileName": "1752892859757_sample.pdf",
      "status": "Approved",
      "tags": ["barangay", "annual", "report", "2024", "comprehensive"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-19T02:41:11.088Z",
      "updatedAt": "2025-07-19T04:40:06.121Z",
      "archivedMetadata": {
        "dateArchived": "2025-07-19T03:57:27.059Z",
        "archivedBy": "68725094719ee6052f54bb39",
        "notes": "Archived due to delet"
      },
      "category": "IT Department",
      "categoryID": "68776346bc4a051d05a6c173",
      "admin": "68725094719ee6052f54bb39",
      "admin_first_name": "Juan",
      "admin_last_name": "Dela Cruz",
      "officer": "68778256129d069cedc152cb",
      "officer_first_name": "Juan",
      "officer_last_name": "Dela Cruz"
    },
    {
      "_id": "687b05c7b14b994f291992c5",
      "title": "Q2 Financial Statement",
      "summary": "Detailed financial report for the second quarter, including income and expenses.",
      "author": "Anna Reyes",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1752950000/Government%20Archiving/finance/q2_financial.pdf",
      "fileName": "q2_financial_statement.pdf",
      "status": "Pending",
      "tags": ["finance", "quarterly", "statement", "2025"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-18T10:00:00.000Z",
      "updatedAt": "2025-07-18T10:00:00.000Z",
      "category": "Finance Department",
      "categoryID": "finance_dept_id",
      "admin": "admin_finance_id",
      "admin_first_name": "Pedro",
      "admin_last_name": "Santos",
      "officer": "officer_finance_id",
      "officer_first_name": "Maria",
      "officer_last_name": "Garcia"
    },
    {
      "_id": "687b05c7b14b994f291992c6",
      "title": "New Policy on Waste Management",
      "summary": "An updated policy document outlining new guidelines for waste segregation and disposal in the community.",
      "author": "Council Member Lim",
      "fullText": "DOCX",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753000000/Government%20Archiving/environment/waste_policy.docx",
      "fileName": "new_waste_policy.docx",
      "status": "Approved",
      "tags": ["policy", "environment", "waste", "management"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-17T15:30:00.000Z",
      "updatedAt": "2025-07-17T15:30:00.000Z",
      "category": "Environment Department",
      "categoryID": "env_dept_id",
      "admin": "admin_env_id",
      "admin_first_name": "Luz",
      "admin_last_name": "Mercado",
      "officer": "officer_env_id",
      "officer_first_name": "Roberto",
      "officer_last_name": "Cruz"
    },
    {
      "_id": "687b05c7b14b994f291992c7",
      "title": "Infrastructure Project Proposal - Phase 1",
      "summary": "Proposal for the new road construction project, including budget and timeline.",
      "author": "Engr. David Lee",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753050000/Government%20Archiving/engineering/road_project.pdf",
      "fileName": "infra_project_proposal_phase1.pdf",
      "status": "Pending",
      "tags": ["infrastructure", "project", "road", "proposal"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-16T09:00:00.000Z",
      "updatedAt": "2025-07-16T09:00:00.000Z",
      "category": "Engineering Department",
      "categoryID": "eng_dept_id",
      "admin": "admin_eng_id",
      "admin_first_name": "Sophia",
      "admin_last_name": "Go",
      "officer": "officer_eng_id",
      "officer_first_name": "Michael",
      "officer_last_name": "Tan"
    },
    {
      "_id": "687b05c7b14b994f291992c8",
      "title": "Community Meeting Minutes - July 10, 2025",
      "summary": "Official minutes from the last community general assembly meeting.",
      "author": "Barangay Secretary",
      "fullText": "DOCX",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753100000/Government%20Archiving/community/meeting_minutes_july10.docx",
      "fileName": "community_meeting_minutes_july10.docx",
      "status": "Approved",
      "tags": ["community", "meeting", "minutes", "assembly"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-15T14:00:00.000Z",
      "updatedAt": "2025-07-15T14:00:00.000Z",
      "category": "Office of the Secretary",
      "categoryID": "secretary_office_id",
      "admin": "admin_sec_id",
      "admin_first_name": "Cristina",
      "admin_last_name": "Aquino",
      "officer": "officer_sec_id",
      "officer_first_name": "Carlo",
      "officer_last_name": "Ramos"
    },
    {
      "_id": "687b05c7b14b994f291992c9",
      "title": "Rejected Grant Application - Environmental Fund",
      "summary": "Application for environmental grant was rejected due to incomplete documentation.",
      "author": "Dept. of Environment",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753150000/Government%20Archiving/grants/rejected_env_grant.pdf",
      "fileName": "rejected_env_grant_application.pdf",
      "status": "Rejected",
      "tags": ["grant", "application", "rejected", "environment"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-14T11:00:00.000Z",
      "updatedAt": "2025-07-14T11:00:00.000Z",
      "category": "Grants and Partnerships",
      "categoryID": "grants_dept_id",
      "admin": "admin_grants_id",
      "admin_first_name": "Isabel",
      "admin_last_name": "Reyes",
      "officer": "officer_grants_id",
      "officer_first_name": "Kevin",
      "officer_last_name": "Lim"
    },
    {
      "_id": "687b05c7b14b994f291992ca",
      "title": "Health Program Proposal - Dengue Prevention",
      "summary": "Proposal for a new community health program focused on dengue prevention.",
      "author": "Dr. Elena Santos",
      "fullText": "PPTX",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753200000/Government%20Archiving/health/dengue_prevention.pptx",
      "fileName": "health_program_dengue_prevention.pptx",
      "status": "Pending",
      "tags": ["health", "program", "dengue", "prevention"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-13T09:30:00.000Z",
      "updatedAt": "2025-07-13T09:30:00.000Z",
      "category": "Health Services",
      "categoryID": "health_dept_id",
      "admin": "admin_health_id",
      "admin_first_name": "Jose",
      "admin_last_name": "Gomez",
      "officer": "officer_health_id",
      "officer_first_name": "Diana",
      "officer_last_name": "Yap"
    },
    {
      "_id": "687b05c7b14b994f291992cb",
      "title": "Barangay Ordinance No. 5 - Noise Pollution",
      "summary": "New ordinance addressing noise pollution within barangay premises.",
      "author": "Legal Department",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753250000/Government%20Archiving/legal/noise_ordinance.pdf",
      "fileName": "barangay_ordinance_noise_pollution.pdf",
      "status": "Approved",
      "tags": ["ordinance", "legal", "noise", "pollution"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-12T16:00:00.000Z",
      "updatedAt": "2025-07-12T16:00:00.000Z",
      "category": "Legal Department",
      "categoryID": "legal_dept_id",
      "admin": "admin_legal_id",
      "admin_first_name": "Anna",
      "admin_last_name": "Cruz",
      "officer": "officer_legal_id",
      "officer_first_name": "Miguel",
      "officer_last_name": "Lim"
    },
    {
      "_id": "687b05c7b14b994f291992cc",
      "title": "Youth Sports League Registration Forms",
      "summary": "Batch of registration forms for the upcoming youth sports league.",
      "author": "Sports Committee",
      "fullText": "XLSX",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753300000/Government%20Archiving/sports/youth_sports_registration.xlsx",
      "fileName": "youth_sports_league_forms.xlsx",
      "status": "Pending",
      "tags": ["youth", "sports", "registration", "league"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-11T10:00:00.000Z",
      "updatedAt": "2025-07-11T10:00:00.000Z",
      "category": "Sports and Youth Development",
      "categoryID": "sports_dept_id",
      "admin": "admin_sports_id",
      "admin_first_name": "Carlo",
      "admin_last_name": "Perez",
      "officer": "officer_sports_id",
      "officer_first_name": "Sofia",
      "officer_last_name": "Santos"
    },
    {
      "_id": "687b05c7b14b994f291992cd",
      "title": "Disaster Preparedness Plan 2025",
      "summary": "Annual plan for disaster preparedness and response.",
      "author": "Disaster Management Office",
      "fullText": "PDF",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753350000/Government%20Archiving/disaster/disaster_plan.pdf",
      "fileName": "disaster_preparedness_plan_2025.pdf",
      "status": "Approved",
      "tags": ["disaster", "preparedness", "plan", "2025"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-10T08:00:00.000Z",
      "updatedAt": "2025-07-10T08:00:00.000Z",
      "category": "Disaster Management",
      "categoryID": "disaster_dept_id",
      "admin": "admin_disaster_id",
      "admin_first_name": "Ramon",
      "admin_last_name": "Soriano",
      "officer": "officer_disaster_id",
      "officer_first_name": "Jessica",
      "officer_last_name": "Ramos"
    },
    {
      "_id": "687b05c7b14b994f291992ce",
      "title": "Budget Proposal for Community Beautification",
      "summary": "A proposal outlining the budget for initiatives aimed at beautifying public spaces.",
      "author": "Community Development Unit",
      "fullText": "XLSX",
      "fileUrl": "https://res.cloudinary.com/dskqeyqns/raw/upload/v1753400000/Government%20Archiving/community/beautification_budget.xlsx",
      "fileName": "community_beautification_budget.xlsx",
      "status": "Rejected",
      "tags": ["budget", "community", "beautification", "proposal"],
      "ArchivedStatus": "Active",
      "createdAt": "2025-07-09T13:00:00.000Z",
      "updatedAt": "2025-07-09T13:00:00.000Z",
      "category": "Community Development",
      "categoryID": "comm_dev_id",
      "admin": "admin_comm_dev_id",
      "admin_first_name": "Grace",
      "admin_last_name": "Tan",
      "officer": "officer_comm_dev_id",
      "officer_first_name": "Leo",
      "officer_last_name": "Gonzales"
    }
  ]
};

export const mockNotifications = [
  {
    id: 'notif1',
    type: 'document_status',
    message: 'Barangay Annual Report 2024 has been **Approved** by Admin Juan Dela Cruz.',
    timestamp: '2025-07-19T05:00:00Z',
    isRead: false,
    documentId: '687b05c7b14b994f291992c4',
  },
  {
    id: 'notif2',
    type: 'new_document',
    message: 'New document "Infrastructure Project Proposal - Phase 1" submitted by Engr. David Lee.',
    timestamp: '2025-07-18T11:30:00Z',
    isRead: false,
    documentId: '687b05c7b14b994f291992c7',
  },
  {
    id: 'notif3',
    type: 'document_status',
    message: 'Q2 Financial Statement is **Pending** Admin approval.',
    timestamp: '2025-07-18T10:15:00Z',
    isRead: true,
    documentId: '687b05c7b14b994f291992c5',
  },
  {
    id: 'notif4',
    type: 'system_alert',
    message: 'Storage usage is at 80%. Consider archiving old documents.',
    timestamp: '2025-07-17T09:00:00Z',
    isRead: false,
  },
  {
    id: 'notif5',
    type: 'document_status',
    message: 'Budget Proposal for Community Beautification has been **Rejected** by Admin Grace Tan.',
    timestamp: '2025-07-10T14:00:00Z',
    isRead: true,
    documentId: '687b05c7b14b994f291992ce',
  },
];